### ISSUE TITLE
Series current duration not appearing

### ISSUE THREAD

**Issue by CallMeVorex** [sleeyax/stremio-discord#4]
When watching a series or movie the current duration isnt appearing in my discord status, just appears with the placeholder's with the stremio link and "All the video content you enjoy in one place", i read through an issue already on the github and used "npm install" for the stremio discord sdk addon but that didnt change anything, some further assitance would be appreciated

**Comment by sleeyax** [comment]
> i read through an issue already on the github and used "npm install" for the stremio discord sdk addon but that didnt change anything

I don't know where you found this, but you don't have to install anything. Either install stremio-discord through PMS or run it manually.

This issue or may not be fixed in 1.1.0. Reopen if that's not the case. Also see https://github.com/sleeyax/stremio-discord/issues/2#issuecomment-578397666 for an explanation on the limitations of this addon.
