### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by AktasC** [sleeyax/stremio-discord#5]
After downloading it, installing it in Stremio's desktop app and restarting both Discord and Stremio it still didn't show up.  
Might need an update

**Comment by sleeyax** [comment]
I fixed some issues and it should work again now. Open a new issue if you encounter another problem, but please keep in mind that there are [Stremio limitations](https://github.com/sleeyax/stremio-discord/issues/2#issuecomment-578397666) and due to that, this addon is more of a hack than an actual solution so it might not always work as you might expect.
